Fixed classification output shape
triton-inference-server/server pull request #1984
Opened 2020-09-04 16:31 UTC by huntrax11

The request parameter named `classification_count` could exceed the class count of the model.

https://github.com/triton-inference-server/server/blob/7793fe74eb375307801770251abbc2110b2766cd/src/servers/classification.cc#L46-L64

2020-09-04 18:47 UTC, deadeyegoodwin commented
http_server.cc seems broken in a similar way. The code there could use some other cleanup to consolidate the classification case.

2020-09-05 07:10 UTC, huntrax11 commented
@deadeyegoodwin Reflected your review.

2020-09-09 18:06 UTC, deadeyegoodwin requested changes

2020-09-09 18:06 UTC, deadeyegoodwin commented on src/servers/grpc_server.cc
> +      output->add_shape(batch1_element_count);
This needs to be min(classification_count, batch1_element_count)

2020-09-09 18:06 UTC, deadeyegoodwin commented on src/servers/http_server.cc
> +      RETURN_IF_ERR(shape_json.AppendUInt(batch1_element_count));
min(info->class_cnt_, batch1_element_count)

2020-09-09 22:32 UTC, huntrax11 commented
@deadeyegoodwin Covered the case you mention.

2020-09-09 23:08 UTC, deadeyegoodwin commented
Those changes look ok. Unfortunately our L0_infer CI test is failing with this PR so can't merge it yet. Are you able to run the CI tests? https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/test.html

2020-09-10 06:21 UTC, huntrax11 commented
@deadeyegoodwin `L0_infer` passes.
```
root@576bb4c846fb:/opt/tritonserver/qa/L0_infer# ./test.sh
=== Running /opt/tritonserver/bin/tritonserver --model-repository=/opt/tritonserver/qa/L0_infer/models --exit-timeout-secs=120
=== Running /opt/tritonserver/bin/tritonserver --model-repository=/opt/tritonserver/qa/L0_infer/models --exit-timeout-secs=120

***
*** Test Passed
***
```

2020-09-10 18:55 UTC, deadeyegoodwin approved these changes

2020-09-10 18:56 UTC, merged