Cleanup deprecated Caffe2 backend and relevant tests
triton-inference-server/server pull request #2124
Opened 2020-10-14 22:08 UTC by CoderHam

2020-10-15 16:54 UTC, deadeyegoodwin requested changes

2020-10-15 16:54 UTC, deadeyegoodwin commented on qa/L0_lifecycle/lifecycle_test.py
> -            for base_name in ["savedmodel", 'netdef']:
For all these lifecycle tests it is important the we don't just remove netdef but that we replace it with something else. An onnx model would be best.

2020-10-15 16:54 UTC, deadeyegoodwin commented on qa/L0_lifecycle/test.sh
> -for i in netdef plan ; do
don't just remove netdef, replace with onnx

2020-10-15 16:54 UTC, deadeyegoodwin commented on qa/L0_sequence_corrid_batcher/test.sh
> -        $DATADIR/qa_dyna_sequence_model_repository/netdef_dyna_sequence_int32 ; do
Need to put "; do" on previous line

2020-10-15 16:54 UTC, deadeyegoodwin commented on qa/L0_server_status/server_status_test.py
> -        for platform in ('graphdef', 'netdef'):
For these tests I think it is ok to remove "netdef" without a replacement, but keep the for loop in case we want to add something back later.

2020-10-15 16:58 UTC, deadeyegoodwin commented
@CoderHam  Also change the description of the commit to explicitly say "Remove Caffe2 backend..."

2020-10-19 20:30 UTC, CoderHam commented on build.py
> +    '20.11dev_nocaffe2': ('20.09', '1.4.0', '2020.2')  # 2.5.0dev_nocaffe2
Note: Will remove `nocaffe2` from both branches are successfully CI

2020-10-19 22:43 UTC, deadeyegoodwin approved these changes

2020-10-20 19:42 UTC, deadeyegoodwin approved these changes

2020-10-20 19:42 UTC, merged