Add java client
triton-inference-server/server pull request #2320
Opened 2020-12-08 21:58 UTC by sujitb-nvidia

This adds a java client library. The examples folder contains scala and java samples, the scala example is more comprehensive and shows how to use model and server API, apart from simple model inference

2020-12-08 22:15 UTC, deadeyegoodwin commented
Can you change the description to say something like: "Add an example showing how to use protoc compiler to generate a GRPC client library for java. The example folder contains ... "

2020-12-08 22:23 UTC, deadeyegoodwin requested changes
Don't include the 3 generated files in the commit.

2020-12-08 22:23 UTC, deadeyegoodwin commented on src/clients/java/README.md
> +
Add title: "Example Java and Scale Client Using Generated GRPC API"

2020-12-08 22:23 UTC, deadeyegoodwin commented on src/clients/java/README.md
> +
Remove the extra blank lines in this file

2020-12-08 22:23 UTC, deadeyegoodwin commented on src/clients/java/README.md
> +/server/src/core/](https://github.com/triton-inference-server/server/tree/master/src/core). The Libray should look as below.
Libray -> "After copying the library directory should look ..."

2020-12-08 22:23 UTC, deadeyegoodwin commented on src/clients/java/README.md
> +see the __examples__ project which has __scala__ and __java__ sample client.
see -> See

2020-12-08 22:23 UTC, deadeyegoodwin commented on src/clients/java/README.md
> +cd library
Put '$' in front for example cmdline:

$ cd library
$ cp ...

2020-12-08 22:23 UTC, deadeyegoodwin commented on src/clients/java/README.md
> +mvn compile
$

2020-12-08 22:23 UTC, deadeyegoodwin commented on src/clients/java/README.md
> +cd examples
$
Combine these into one ``` region.

2020-12-08 22:23 UTC, deadeyegoodwin commented on src/clients/java/examples/src/main/java/clients/SimpleJavaClient.java
> +package clients;
Add copyright to this file. You can find it in any other source file

2020-12-08 22:23 UTC, deadeyegoodwin commented on src/clients/java/examples/src/main/scala/clients/SimpleClient.scala
> +package clients
copyright

2020-12-09 20:05 UTC, deadeyegoodwin commented
@sujitbiswas BTW, I'm not going to look at any updates until you let me know they are ready. You can do this by using the "re-request review" button next to my name in the upper right of the page.

2020-12-09 20:19 UTC, sujitb-nvidia commented
> @sujitbiswas BTW, I'm not going to look at any updates until you let me know they are ready. You can do this by using the "re-request review" button next to my name in the upper right of the page.

Okay @deadeyegoodwin

2020-12-09 23:28 UTC, deadeyegoodwin approved these changes

2020-12-10 19:30 UTC, merged