Add libmkl_vml_def.so
triton-inference-server/server pull request #2406
Opened 2021-01-12 22:27 UTC by CoderHam

- Needed by PyTorch for CPU model execution

2021-01-12 23:04 UTC, deadeyegoodwin approved these changes

2021-01-13 21:12 UTC, CoderHam commented
Rebased and ready to merge

2021-01-13 21:54 UTC, deadeyegoodwin approved these changes

2021-01-14 17:55 UTC, deadeyegoodwin reviewed
Don't you need to also explicitly link this library into libtriton_pytorch.so as we did with the other libraries?

2021-01-14 17:56 UTC, CoderHam commented
> Don't you need to also explicitly link this library into libtriton_pytorch.so as we did with the other libraries?

Yes, I forgot to create the PR for it. I was already ready. Doing it now.

2021-01-14 21:29 UTC, deadeyegoodwin requested changes

2021-01-14 21:29 UTC, deadeyegoodwin commented on build.py
> +COPY --from=tritonserver_pytorch /opt/conda/lib//libmkl_vml_def.so /opt/tritonserver/backends/pytorch/
You have an extra backslash in there...

2021-01-14 22:52 UTC, deadeyegoodwin approved these changes

2021-01-14 22:52 UTC, merged