Feature/s3integration
triton-inference-server/server pull request #2494
Opened 2021-02-08 11:52 UTC by sinaure

s3 integration via secret creds

2021-02-09 01:55 UTC, deadeyegoodwin commented
@sinaure  This seems to replace your earlier PR, is that correct?
Please check https://github.com/triton-inference-server/server/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla for the CLA and submit it as instructed so that we can accept this submission.

2021-02-09 02:00 UTC, deadeyegoodwin requested changes
Change is generally OK but don't change the default behavior of the existing as it is referenced in the README. You should add a section to the README describing how the S3 configuration can be used.

2021-02-09 09:14 UTC, sinaure commented on deploy/single_server/templates/s3-secret.yaml
> +{{- if .Values.s3.enabled }}
line 62

2022-09-14 18:36 UTC, rmccorm4 commented
Closing as we have an AWS/S3 example that supports secrets: https://github.com/triton-inference-server/server/tree/main/deploy/aws.

2022-09-14 18:36 UTC, closed without merging