Expose cmdline option to set repo agent directory. Fix repo agent invoke order. Fix test
triton-inference-server/server pull request #2511
Opened 2021-02-11 21:18 UTC by GuanLuo

2021-02-11 22:54 UTC, CoderHam requested changes

2021-02-11 22:54 UTC, CoderHam commented on src/core/model_repository_manager.cc
> +        for (size_t idx = 0; idx < agent_models_.size(); --idx) {
This should be ++idx right?

2021-02-11 23:49 UTC, deadeyegoodwin requested changes

2021-02-11 23:49 UTC, deadeyegoodwin commented on src/core/tritonserver.cc
> +  std::string repoagent_dir_;
Initialize this to default value in the TritonServerOptions constructor

2021-02-12 00:13 UTC, GuanLuo commented on src/core/model_repository_manager.cc
> +        for (size_t idx = 0; idx < agent_models_.size(); --idx) {
Sorry, typo..

2021-02-12 17:31 UTC, merged