Add option to inform TensorRT backend to prepare next batch early
triton-inference-server/server pull request #2527
Opened 2021-02-18 00:47 UTC by GuanLuo

2021-02-18 01:13 UTC, GuanLuo commented
This PR is likely going to have conflict with #2523 and #2510 , will resolve the conflicts as they are merged into master

2021-02-18 02:47 UTC, deadeyegoodwin requested changes

2021-02-18 02:47 UTC, deadeyegoodwin commented on src/backends/tensorrt/plan_backend.cc
> +  // If premature batching is set, we duplicate the context idx in
"premature" can have a negative connotation. Let's call it "eager batching"

2021-02-18 18:08 UTC, deadeyegoodwin submitted a review, later dismissed

2021-02-25 00:22 UTC, deadeyegoodwin approved these changes

2021-02-25 01:44 UTC, merged