Fix non-GPU build
triton-inference-server/server pull request #2561
Opened 2021-02-25 22:37 UTC by GuanLuo

2021-02-25 23:24 UTC, CoderHam requested changes

2021-02-25 23:24 UTC, CoderHam commented on src/core/backend_context.cc
> +  LOG_ERROR << "before launching gather kernel";
Did you mean to add these temporarily for logging. I think they should be removed.

2021-02-25 23:24 UTC, CoderHam commented on src/core/backend_context.cc
> +    LOG_ERROR << "gather kernel launched with status: " << status.AsString();
Same here.

2021-02-25 23:34 UTC, CoderHam approved these changes

2021-02-25 23:59 UTC, deadeyegoodwin commented
@GuanLuo  It seems like that extra logging for every request could have had an impact of perf. What do you think?

2021-02-26 00:07 UTC, GuanLuo commented
That is debug logging for checking PTX.. Removed from this PR

2021-02-26 01:05 UTC, deadeyegoodwin approved these changes

2021-02-26 19:30 UTC, merged