Fix TRT backend to capture timestamp as soon as possible
triton-inference-server/server pull request #2602
Opened 2021-03-09 01:56 UTC by GuanLuo

The timestamp captured for each phase is more realistic:
resnet before:
`Avg request latency: 4254 usec (overhead 2 usec + queue 72 usec + compute input 920 usec + compute infer 3244 usec + compute output 16 usec)`
resnet after:
`Avg request latency: 4348 usec (overhead 2 usec + queue 73 usec + compute input 312 usec + compute infer 3930 usec + compute output 31 usec)`

But there is additional overhead introduced by the fix, which is obvious for small model (end-to-end < 1ms):
plan_zero_1_float32 before:
`Avg request latency: 101 usec (overhead 1 usec + queue 13 usec + compute input 76 usec + compute infer 7 usec + compute output 4 usec)`
after:
`Avg request latency: 130 usec (overhead 3 usec + queue 13 usec + compute input 58 usec + compute infer 23 usec + compute output 33 usec)`

2021-03-10 02:42 UTC, GuanLuo commented
Reverted part of the change to still let `ProcessResponse()` check "input consumed event". This is to prevent the `ProcessResponse()` backlog in the edge case where the responses take time to be finalized and to be sent: consider a case where model execution time < response thread's turn around time, decoupling the check from response thread will cause the backend keep taking batches from scheduler while the response thread is backlogged.

2021-03-10 17:18 UTC, deadeyegoodwin requested changes

2021-03-10 17:18 UTC, deadeyegoodwin commented on src/backends/tensorrt/plan_backend.cc
> +  RETURN_IF_ERROR(context->CreateCudaStream(
TRITON_ENABLE_STATS

2021-03-10 17:18 UTC, deadeyegoodwin commented on src/backends/tensorrt/plan_backend.cc
> +    RETURN_IF_ERROR(CreateCudaEvent(
TRITON_ENABLE_STATS

2021-03-12 21:52 UTC, deadeyegoodwin approved these changes

2021-03-16 02:09 UTC, merged