Added python script to check the valgrind logs, removed bash function
triton-inference-server/server pull request #2646
Opened 2021-03-19 00:00 UTC by aramesh7

2021-03-19 07:34 UTC, tanmayv25 commented
Why is this needed? To clarify, I do prefer python script to a bash function. Trying to understand the motivation.

2021-03-19 07:49 UTC, aramesh7 commented
> Why is this needed? To clarify, I do prefer python script to a bash function. Trying to understand the motivation.

The way the `check_valgrind_log` bash function was splitting up the leak records required that they be of a minimum length. Sometimes this would result in missed leaks, or false positives. With the python script, you can cleanly separate the leak records. In the future, if we encounter leaks with hidden stack traces, we can increase the number of callers shown on the stack trace, and the script can already accomodate this. With the bash function you would need to go back and change the number of lines emitted by grep.

2021-03-23 21:22 UTC, CoderHam commented
@aramesh7 was the CI failure fixed for this?

2021-03-23 22:48 UTC, aramesh7 commented
> @aramesh7 was the CI failure fixed for this?

Yes, all the related tests pass.

2021-03-23 23:10 UTC, CoderHam requested changes

2021-03-23 23:10 UTC, CoderHam commented on qa/common/check_valgrind_log.py
> +# Copyright (c) 2018-2020, NVIDIA CORPORATION. All rights reserved.
Fix Copyright

2021-03-23 23:24 UTC, CoderHam approved these changes

2021-03-24 00:01 UTC, deadeyegoodwin approved these changes

2021-03-24 00:01 UTC, merged