Use protobuf files from common repo
triton-inference-server/server pull request #2730
Opened 2021-04-14 23:28 UTC by deadeyegoodwin

2021-04-15 01:42 UTC, GuanLuo submitted a review, later dismissed

2021-04-20 21:40 UTC, CoderHam requested changes
I noticed the jetson build failed for this pipeline. Around test-util build I believe:

```
fatal error: model_config.pb.h: No such file or directory
 #include "model_config.pb.h"
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
````

2021-04-20 21:40 UTC, CoderHam commented on build/server/CMakeLists.txt
> +  )
Remove extra spacing before ')'

2021-04-20 21:40 UTC, CoderHam commented on src/backends/backend/CMakeLists.txt
> +    proto-library
Add comment # repo-common just like we do for  L71/72. Also in the other files

2021-04-20 21:40 UTC, CoderHam commented on src/test/custom/sdk/CMakeLists.txt
> +#install(
Did you mean to remove this?

2021-05-04 06:41 UTC, CoderHam commented
Some tests require the proto files: L0_simple_go_client and L0_client_java
They copy these over from src/core in the Docker QA and will likely need to be modified for the new location of the proto files.

2021-05-11 15:40 UTC, merged