Improve python backend testing
triton-inference-server/server pull request #2749
Opened 2021-04-21 02:38 UTC by Tabrizian

2021-04-21 23:31 UTC, deadeyegoodwin approved these changes

2021-04-22 04:55 UTC, CoderHam requested changes
```
| python_nobatch_int8_int8_int8                       | 1       | UNAVAILABLE: Internal: Failed to initialize the model instance python_nobatch_int8_int8_int8_0 because it run out of shared memory. Increase the shared memory size to fix this error.          |
```
L0_infer failures. You might need to increase the shared memory size just for that test. Additionally this might be true for other tests so just have a deeper look.

2021-04-22 20:35 UTC, deadeyegoodwin approved these changes

2021-04-22 20:39 UTC, Tabrizian commented
I fixed the error on the gitlab side by increasing the shared memory size.

2021-04-24 18:25 UTC, CoderHam approved these changes

2021-04-26 14:36 UTC, merged