Update README and docs post-21.05 release
triton-inference-server/server pull request #2904
Opened 2021-05-21 17:18 UTC by dzier

2021-05-21 17:35 UTC, deadeyegoodwin requested changes

2021-05-21 17:35 UTC, deadeyegoodwin commented on README.md
>  release of the Triton Inference Server is 2.9.0 and is available on
latest release is 2.10.0

2021-05-21 18:41 UTC, CoderHam requested changes
Please cherry pick change from #2905

2021-05-25 16:12 UTC, CoderHam commented
@dzier did you pick up the doc fix I mentioned here?

> Please cherry pick change from #2905

2021-05-25 16:29 UTC, deadeyegoodwin submitted a review, later dismissed

2021-05-25 17:03 UTC, deadeyegoodwin approved these changes

2021-05-25 17:04 UTC, merged