[WIP] Add test for host policy. Fix edge case
triton-inference-server/server pull request #3049
Opened 2021-06-25 04:25 UTC by GuanLuo

2021-06-25 22:48 UTC, GuanLuo commented
Will create follow up PR to update L0_io when we apply the same to other backends.

2021-06-25 22:56 UTC, deadeyegoodwin requested changes

2021-06-25 22:56 UTC, deadeyegoodwin commented on src/backends/backend/triton_backend_manager.cc
> +// Copyright (c) 2020-2021, NVIDIA CORPORATION & AFFILIATES. All rights
Remove the "(c)" to avoid this line wrap... it will cause L0_copyright to fail

2021-06-25 22:56 UTC, deadeyegoodwin commented on src/backends/backend/triton_model_instance.cc
> +// Copyright (c) 2020-2021, NVIDIA CORPORATION & AFFILIATES. All rights
Remove the "(c)" to avoid this line wrap... it will cause L0_copyright to fail

2021-06-25 23:05 UTC, deadeyegoodwin submitted a review, later dismissed

2021-06-25 23:59 UTC, deadeyegoodwin approved these changes

2021-06-28 16:25 UTC, deadeyegoodwin approved these changes

2021-06-28 20:52 UTC, CoderHam requested changes

2021-06-28 20:52 UTC, CoderHam commented on src/core/infer_request.cc
>  }
Please update copyright, and remaining source files that require updates

2021-06-28 23:48 UTC, CoderHam approved these changes

2021-06-29 00:03 UTC, deadeyegoodwin approved these changes

2021-06-29 01:35 UTC, merged