update version for ort
triton-inference-server/server pull request #3199
Opened 2021-08-04 19:38 UTC by askhade

Update ORT version.

2021-08-04 20:33 UTC, GuanLuo approved these changes

2021-08-06 19:17 UTC, CoderHam requested changes

2021-08-06 19:17 UTC, CoderHam commented on build.py
> +        '-DTRITON_ENABLE_ONNXRUNTIME_TENSORRT=ON',
We should enable ORT for Jetpack in a subsequent PR since it will manually building ORT on jetson first to unblock the CI.

2021-08-09 17:10 UTC, deadeyegoodwin commented
This change is incorporated into r21.08 branch. Closing.

2021-08-09 17:10 UTC, closed without merging