Update base software for windows 21.08 release
triton-inference-server/server pull request #3205
Opened 2021-08-05 21:26 UTC by deadeyegoodwin

2021-08-06 19:16 UTC, CoderHam requested changes

2021-08-06 19:16 UTC, CoderHam commented on build.py
> +        '-DTRITON_ENABLE_ONNXRUNTIME_TENSORRT=ON',
We should hold off on enabling TRT support for jetpack till I add in the updated ORT build (1.8.1) which enables TRT 8 support.

2021-08-06 19:16 UTC, CoderHam commented on docs/build.md
>  * For cuDNN the CUDNN_VERSION and CUDNN_ZIP arguments indicate the
Add a comma after "For cuDNN"

2021-08-06 19:16 UTC, CoderHam commented on Dockerfile.win10.min
> +ARG TENSORRT_ZIP=TensorRT-${TENSORRT_VERSION}.Windows10.x86_64.cuda-11.3.cudnn8.2.zip
Should this not be 11.4 instead of 11.3?

2021-08-09 17:10 UTC, deadeyegoodwin commented
This change is incorporated into r21.08 branch. Closing.

2021-08-09 17:10 UTC, closed without merging