add tests for trt options
triton-inference-server/server pull request #3315
Opened 2021-09-02 21:23 UTC by askhade

2021-09-02 21:46 UTC, askhade commented
@efeguney: Cant add you as reviewer here so tagging you instead.

2021-09-02 23:08 UTC, deadeyegoodwin requested changes

2021-09-02 23:08 UTC, deadeyegoodwin commented on qa/L0_onnxtrt_optimization/test.sh
> +        echo -e "\n***\n*** Failed. Expected TensorRT Execution Accelerator is set\n***"
This message should say something about cache one, perhaps similar to the message 2 above

2021-09-02 23:09 UTC, deadeyegoodwin commented
@askhade  Can you also rebase to main

2021-09-02 23:57 UTC, deadeyegoodwin commented
> 
> 
> @askhade Can you also rebase to main

I rebased... I'll start a CI run

2021-09-03 18:20 UTC, deadeyegoodwin approved these changes

2021-09-03 18:20 UTC, merged