Update DCGM version and add better error logging
triton-inference-server/server pull request #3319
Opened 2021-09-02 23:48 UTC by jbkyang-nvi

Update DCGM to 2.2.9 and add better error logging functionalities

2021-09-02 23:51 UTC, deadeyegoodwin requested changes
We also install dcgm in Dockerfile.sdk so version needs update there as well. Also look to see if there is any other place we use it.

2021-09-03 00:17 UTC, jbkyang-nvi commented
> We also install dcgm in Dockerfile.sdk so version needs update there as well. Also look to see if there is any other place we use it.

@deadeyegoodwin  Dockerfile.sdk's DCGM is for the model analyzer. Updated both

2021-09-03 14:28 UTC, Tabrizian approved these changes

2021-09-03 16:16 UTC, deadeyegoodwin approved these changes

2021-09-03 17:57 UTC, merged