Add MLflow plugin
triton-inference-server/server pull request #3540
Opened 2021-11-06 04:36 UTC by GuanLuo

2021-11-09 18:50 UTC, deadeyegoodwin requested changes

2021-11-09 18:50 UTC, deadeyegoodwin commented on deploy/mlflow-triton-plugin/README.md
> +# Copyright 2018-2021, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
Just 2021?

2021-11-09 18:50 UTC, deadeyegoodwin commented on deploy/mlflow-triton-plugin/README.md
> +The `publish_model_to_mlflow.py` script is used to publish `triton` flavor models
Is "flavors" the way mlflow refers to different model formats?

2021-11-09 18:50 UTC, deadeyegoodwin commented on deploy/mlflow-triton-plugin/README.md
> +cd /mlflow/scripts
"cd scripts"

2021-11-09 18:50 UTC, deadeyegoodwin commented on deploy/mlflow-triton-plugin/README.md
> +python publish_model_to_mlflow.py --model_name onnx_float32_int32_int32 --model_directory <path-to-the-examples-directory>/onnx_float32_int32_int32 --flavor triton
User will not know what "onnx_float32_int32_int32" is. Describe that it is a simple example model and describe what its inputs and outputs are.

2021-11-09 18:50 UTC, deadeyegoodwin commented on deploy/mlflow-triton-plugin/README.md
> +```
Some explanatory text... perhaps instead of using a heading say something like "Next use mlflow to deploy a model to triton."

2021-11-09 18:50 UTC, deadeyegoodwin commented on deploy/mlflow-triton-plugin/README.md
> +```
Some explanatory text...

2021-11-09 18:50 UTC, deadeyegoodwin commented on deploy/mlflow-triton-plugin/README.md
> +The following deployment functions are implemented within the plugin.
Describe what an mlflow deployment is and how it is supported by Triton

2021-11-09 18:50 UTC, deadeyegoodwin commented on deploy/mlflow-triton-plugin/README.md
> +##### CLI
Instead of '####' headings might be easier to read if you just say "To create deployment using CLI.... You can also create deployment using MLFlows Python API..."

2021-11-09 18:50 UTC, deadeyegoodwin commented on deploy/mlflow-triton-plugin/README.md
> +
Explain how triton support deleting a deployment.

2021-11-09 20:16 UTC, GuanLuo commented on deploy/mlflow-triton-plugin/README.md
> +The `publish_model_to_mlflow.py` script is used to publish `triton` flavor models
Correct. One thing is that they have an official "onnx" flavor which we may enhance this plugin by supporting it. The idea would be taking an additional step to generate the Triton model folder of the ONNX file, and then upload it in the same way as the "Triton flavor".

2021-11-09 20:19 UTC, deadeyegoodwin commented on deploy/mlflow-triton-plugin/README.md
> +The `publish_model_to_mlflow.py` script is used to publish `triton` flavor models
Please file a ticket to track that enhancement.

2021-11-10 17:33 UTC, deadeyegoodwin approved these changes
What is the plan for testing. At the very least we need to open a ticket and describe what type of CI we need to this plugin. And/or we need to add something to the QA testplan.

2021-11-10 18:59 UTC, merged