Add documentation for ragged batching
triton-inference-server/server pull request #3545
Opened 2021-11-09 07:31 UTC by GuanLuo

2021-11-09 18:20 UTC, tanmayv25 requested changes

2021-11-09 18:20 UTC, tanmayv25 commented on docs/ragged_batching.md
> +[ -1 ] and an additional batch input, INDEX, shape [ -1 ] which the model will
the model should use to interpret

2021-11-09 18:20 UTC, tanmayv25 commented on docs/ragged_batching.md
> +Triton provides dynamic batching feature, which combines multiple requests for
Link dynamic batching to the dynamic batching scheduler doc here.

2021-11-09 18:20 UTC, tanmayv25 commented on docs/ragged_batching.md
> +can be dynamically batched only if each input has the same shape across the
By default, the requests can be dynamically batched only if each input has the same shape across the
requests. In order to exploit dynamic batching for a case where input shapes often varies, the client would need to pad the input tensors in the requests to a fixed shape.

2021-11-09 18:20 UTC, tanmayv25 commented on docs/ragged_batching.md
> +such input (ragged input) by setting `allow_ragged_batch` field in the model
Include `allow_ragged_batching` in the model configuration doc and then link this to it

2021-11-09 18:20 UTC, tanmayv25 commented on docs/ragged_batching.md
> +implementation. For backends that are known to support ragged batching
The backends -- such as ONNX Runtime, TensorFlow and TensorRT -- require model to accept inputs as 1-dimensional tensors. These backends concatenate the ragged request inputs into the 1-dimensional tensor.

Also link the ONNX Runtime, TensorFLow and TensorrRT to their respective backend repositories.

2021-11-09 19:08 UTC, deadeyegoodwin requested changes

2021-11-09 19:08 UTC, deadeyegoodwin commented on docs/ragged_batching.md
> +(ONNX Runtime backend, TensorFlow backend, TensorRT backend), they require
Does pytorch not support ragged batching?

2021-11-09 19:08 UTC, deadeyegoodwin commented on docs/ragged_batching.md
> +information about the each batch element, such as the element count
".. about each..."

2021-11-09 19:08 UTC, deadeyegoodwin commented on docs/ragged_batching.md
> +become shape [ 1, 5 ] and thus Triton can batch and send them to the model.
"... and send them to the model as a single [ 3, 5 ] tensor."

2021-11-09 19:08 UTC, deadeyegoodwin commented on docs/ragged_batching.md
> +```
"The above example uses BATCH_ELEMENT_COUNT (protobuf link) type of ragged batching. Other types described in [link] operate similarly."

2021-11-09 21:52 UTC, GuanLuo commented on docs/ragged_batching.md
> +(ONNX Runtime backend, TensorFlow backend, TensorRT backend), they require
No, I don't see it has code to handling ragged batching.

2021-11-09 23:38 UTC, deadeyegoodwin approved these changes

2021-11-10 19:04 UTC, tanmayv25 approved these changes

2021-11-10 19:08 UTC, merged