Refactor InferenceBackend to Model. Related code cleanup
triton-inference-server/server pull request #3587
Opened 2021-11-18 22:43 UTC by GuanLuo

The commit Rename InferenceBackend to Model (569f7f4ba3441484ada7850643e3d2dc0bcfdb6e) is just name changes and can be skipped

2021-11-19 20:35 UTC, tanmayv25 commented
Looks good clean up. We can also move the files from `src/backends/` to `src/core` and remove the backends directory from this repo.

2021-11-19 20:42 UTC, CoderHam requested changes
Minor changes else LGTM

2021-11-19 20:42 UTC, CoderHam commented on src/backends/backend/triton_model.cc
> +  // If 'sequence_batching' is configured use the SequenceBatchScheduler,
configured, then use

2021-11-19 20:42 UTC, CoderHam commented on src/core/model_config.h
>  using BackendCmdlineConfigMap =
update copyright

2021-11-19 20:42 UTC, CoderHam commented on src/backends/ensemble/ensemble_model.cc
>  // (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
Fix copyright

2021-11-19 20:42 UTC, CoderHam commented on src/backends/ensemble/ensemble_model.h
>  #pragma once
Fix copyright

2021-11-19 20:53 UTC, deadeyegoodwin submitted a review, later dismissed

2021-11-22 18:49 UTC, CoderHam approved these changes

2021-11-22 22:37 UTC, merged