Passing TorchTRT flag
triton-inference-server/server pull request #3605
Opened 2021-11-24 00:27 UTC by borisfom

Signed-off-by: Boris Fomitchev <bfomitchev@nvidia.com>

2021-11-24 00:48 UTC, CoderHam approved these changes

2021-11-24 03:12 UTC, CoderHam requested changes

2021-11-24 03:12 UTC, CoderHam commented on build.py
> +    return cargs
I just noticed there is a return statement before this. Please fix the same here. Moreover the changes from https://github.com/triton-inference-server/server/pull/3606 might supersede this.

2021-11-24 19:56 UTC, CoderHam approved these changes

2021-11-29 19:49 UTC, CoderHam commented
@borisfom looks like there were some changes David G made to build.py that were incorrectly rebased. I will push the changes up shortly

2021-11-29 19:58 UTC, CoderHam approved these changes

2021-11-29 19:59 UTC, GuanLuo approved these changes

2021-11-29 20:19 UTC, tanmayv25 approved these changes

2021-11-30 20:47 UTC, merged