Add tests for explicit model control in Python backend
triton-inference-server/server pull request #3635
Opened 2021-11-30 15:46 UTC by Tabrizian

2021-11-30 17:41 UTC, CoderHam requested changes
Can you change the test name from explicit to model_control / explicit_model_control?

2021-11-30 18:55 UTC, tanmayv25 commented
@Tabrizian Should we add these tests in `lifecycle`? We have explicit model load/reload for other platforms in L0_lifecycle.

2021-11-30 19:00 UTC, tanmayv25 commented on qa/L0_backend_python/explicit/explicit_model_test.py
> +            for _ in range(5):
You can check the `model_name` is not already loaded in the server before proceeding.

2021-12-01 17:56 UTC, Tabrizian commented
@tanmayv25 I looked into L0_lifecycle. It looks like a good place to add Python backend but the tests need some changes to make them compatible with other backends so it can take some time. I created a ticket for it.

2021-12-01 23:52 UTC, tanmayv25 approved these changes

2021-12-02 17:18 UTC, CoderHam approved these changes

2021-12-02 17:20 UTC, merged