Add ONNX flavor support
triton-inference-server/server pull request #3638
Opened 2021-12-01 20:42 UTC by GuanLuo

2021-12-01 22:56 UTC, deadeyegoodwin requested changes

2021-12-01 22:56 UTC, deadeyegoodwin commented on deploy/mlflow-triton-plugin/README.md
> +* flavor
Should this be 'triton'?

2021-12-02 01:08 UTC, GuanLuo commented on deploy/mlflow-triton-plugin/README.md
> +* flavor
Yes, fixed

2021-12-02 01:09 UTC, deadeyegoodwin approved these changes

2021-12-02 01:11 UTC, merged