Improve error message. Add test for TF autofiller to handle scalars
triton-inference-server/server pull request #3670
Opened 2021-12-08 04:13 UTC by tanmayv25

2021-12-08 07:40 UTC, GuanLuo approved these changes

2021-12-08 17:51 UTC, deadeyegoodwin requested changes

2021-12-08 17:51 UTC, deadeyegoodwin commented on qa/L0_tf_unknown_rank/test.sh
> +cp -r $DATADIR/tf_model_store2/scalar_model scalar_repo/
All models in tf_model_store2 must load correct due to other CI tests. scalar_model will need to live in tf_model_store3 or similar new repo.

2021-12-08 21:45 UTC, deadeyegoodwin approved these changes

2021-12-09 20:05 UTC, CoderHam approved these changes

2021-12-09 23:35 UTC, merged