Disable HTTP / GRPC by default if Vertex AI environment is detected
triton-inference-server/server pull request #3691
Opened 2021-12-10 20:44 UTC by GuanLuo

2021-12-10 20:56 UTC, deadeyegoodwin approved these changes

2021-12-10 21:01 UTC, tanmayv25 approved these changes

2021-12-10 21:26 UTC, CoderHam submitted a review, later dismissed

2021-12-13 04:01 UTC, CoderHam requested changes

2021-12-13 04:01 UTC, CoderHam commented on qa/L0_vertex_ai/test.sh
> +SERVER_ARGS=" --model-repository=single_model --allow-grpc=true"
Can you remove the extra space before `--model-repo`

2021-12-13 05:15 UTC, CoderHam approved these changes

2021-12-13 23:11 UTC, merged