On-Prem Kubernetes Deploy Helm Chart
triton-inference-server/server pull request #3709
Opened 2021-12-16 22:49 UTC by nealvaidya

This PR provides a new helm chart and instructions for deploying Triton Inference Server in an on-premises Kubernetes environment. In particular, it includes a horizontal pod autoscaler and Traefik load balancer to replace CSP specific components.

2021-12-24 14:56 UTC, JulesBelveze commented
Hi @nealvaidya I trying to use Triton server to make gRPC requests. I've been following your changes in order to use the load balancer. However, when I deploy the traffic ingress I'm getting the following log errors:
```
time="2021-12-24T14:39:03Z" level=error msg="subset not found for default/triton-server-triton-inference-server" ingress=triton-inference-server-ingress-grpc namespace=default providerName=kubernetescrd
time="2021-12-24T14:39:03Z" level=error msg="subset not found for default/triton-server-triton-inference-server" providerName=kubernetescrd ingress=triton-inference-server-ingress-http namespace=default
time="2021-12-24T14:39:03Z" level=error msg="subset not found for default/triton-server-triton-inference-server" providerName=kubernetescrd ingress=triton-inference-server-ingress-grpc namespace=default
time="2021-12-24T14:39:03Z" level=error msg="subset not found for default/triton-server-triton-inference-server" namespace=default providerName=kubernetescrd ingress=triton-inference-server-ingress-http
time="2021-12-24T14:39:04Z" level=error msg="subset not found for default/triton-server-triton-inference-server" namespace=default providerName=kubernetescrd ingress=triton-inference-server-ingress-grpc
time="2021-12-24T14:39:04Z" level=error msg="subset not found for default/triton-server-triton-inference-server" providerName=kubernetescrd ingress=triton-inference-server-ingress-http namespace=default
time="2021-12-24T14:39:05Z" level=error msg="subset not found for default/triton-server-triton-inference-server" providerName=kubernetescrd ingress=triton-inference-server-ingress-grpc namespace=default
time="2021-12-24T14:39:05Z" level=error msg="subset not found for default/triton-server-triton-inference-server" ingress=triton-inference-server-ingress-http namespace=default providerName=kubernetescrd
time="2021-12-24T14:39:06Z" level=error msg="subset not found for default/triton-server-triton-inference-server" providerName=kubernetescrd ingress=triton-inference-server-ingress-grpc namespace=default
time="2021-12-24T14:39:06Z" level=error msg="subset not found for default/triton-server-triton-inference-server" providerName=kubernetescrd ingress=triton-inference-server-ingress-http namespace=default
time="2021-12-24T14:39:06Z" level=error msg="subset not found for default/triton-server-triton-inference-server" providerName=kubernetescrd ingress=triton-inference-server-ingress-grpc namespace=default
time="2021-12-24T14:39:06Z" level=error msg="subset not found for default/triton-server-triton-inference-server" ingress=triton-inference-server-ingress-http namespace=default providerName=kubernetescrd
time="2021-12-24T14:39:08Z" level=error msg="subset not found for default/triton-server-triton-inference-server" ingress=triton-inference-server-ingress-grpc providerName=kubernetescrd namespace=default
time="2021-12-24T14:39:08Z" level=error msg="subset not found for default/triton-server-triton-inference-server" providerName=kubernetescrd ingress=triton-inference-server-ingress-http namespace=default
time="2021-12-24T14:39:08Z" level=error msg="subset not found for default/triton-server-triton-inference-server" namespace=default providerName=kubernetescrd ingress=triton-inference-server-ingress-grpc
time="2021-12-24T14:39:08Z" level=error msg="subset not found for default/triton-server-triton-inference-server" providerName=kubernetescrd namespace=default ingress=triton-inference-server-ingress-http
time="2021-12-24T14:39:10Z" level=error msg="subset not found for default/triton-server-triton-inference-server" providerName=kubernetescrd ingress=triton-inference-server-ingress-grpc namespace=default
time="2021-12-24T14:39:10Z" level=error msg="subset not found for default/triton-server-triton-inference-server" providerName=kubernetescrd ingress=triton-inference-server-ingress-http namespace=default
time="2021-12-24T14:39:10Z" level=error msg="subset not found for default/triton-server-triton-inference-server" ingress=triton-inference-server-ingress-grpc namespace=default providerName=kubernetescrd
time="2021-12-24T14:39:10Z" level=error msg="subset not found for default/triton-server-triton-inference-server" providerName=kubernetescrd ingress=triton-inference-server-ingress-http namespace=default
time="2021-12-24T14:39:11Z" level=error msg="subset not found for default/triton-server-triton-inference-server" ingress=triton-inference-server-ingress-grpc namespace=default providerName=kubernetescrd
time="2021-12-24T14:39:11Z" level=error msg="subset not found for default/triton-server-triton-inference-server" ingress=triton-inference-server-ingress-http namespace=default providerName=kubernetescrd
time="2021-12-24T14:39:12Z" level=error msg="subset not found for default/triton-server-triton-inference-server" providerName=kubernetescrd ingress=triton-inference-server-ingress-grpc namespace=default
time="2021-12-24T14:39:12Z" level=error msg="subset not found for default/triton-server-triton-inference-server" providerName=kubernetescrd ingress=triton-inference-server-ingress-http namespace=default
time="2021-12-24T14:39:12Z" level=error msg="subset not found for default/triton-server-triton-inference-server" providerName=kubernetescrd ingress=triton-inference-server-ingress-http namespace=default
time="2021-12-24T14:39:12Z" level=error msg="subset not found for default/triton-server-triton-inference-server" ingress=triton-inference-server-ingress-grpc namespace=default providerName=kubernetescrd
time="2021-12-24T14:39:14Z" level=error msg="subset not found for default/triton-server-triton-inference-server" providerName=kubernetescrd ingress=triton-inference-server-ingress-grpc namespace=default
time="2021-12-24T14:39:14Z" level=error msg="subset not found for default/triton-server-triton-inference-server" ingress=triton-inference-server-ingress-http namespace=default providerName=kubernetescrd
time="2021-12-24T14:39:14Z" level=error msg="subset not found for default/triton-server-triton-inference-server" providerName=kubernetescrd ingress=triton-inference-server-ingress-grpc namespace=default
time="2021-12-24T14:39:14Z" level=error msg="subset not found for default/triton-server-triton-inference-server" ingress=triton-inference-server-ingress-http providerName=kubernetescrd namespace=default
time="2021-12-24T14:39:15Z" level=error msg="subset not found for default/triton-server-triton-inference-server" providerName=kubernetescrd ingress=triton-inference-server-ingress-grpc namespace=default
time="2021-12-24T14:39:15Z" level=error msg="subset not found for default/triton-server-triton-inference-server" providerName=kubernetescrd ingress=triton-inference-server-ingress-http namespace=default
time="2021-12-24T14:39:15Z" level=error msg="subset not found for default/triton-server-triton-inference-server" ingress=triton-inference-server-ingress-grpc namespace=default providerName=kubernetescrd
time="2021-12-24T14:39:15Z" level=error msg="subset not found for default/triton-server-triton-inference-server" namespace=default providerName=kubernetescrd ingress=triton-inference-server-ingress-http
time="2021-12-24T14:39:16Z" level=error msg="subset not found for default/triton-server-triton-inference-server" providerName=kubernetescrd ingress=triton-inference-server-ingress-grpc namespace=default
time="2021-12-24T14:39:16Z" level=error msg="subset not found for default/triton-server-triton-inference-server" providerName=kubernetescrd ingress=triton-inference-server-ingress-http namespace=default
```
any idea what could have gone wrong? Thanks for your help!

2022-01-13 20:03 UTC, deadeyegoodwin requested changes
Why was qa/ensemble_models/nobatch_to_batch_nobatch_float32_float32_float32/config.pbtxt deleted? Please remove that from the PR and I will merge.

2022-01-13 22:08 UTC, deadeyegoodwin approved these changes

2022-01-13 22:08 UTC, merged

2024-07-10 17:40 UTC, mistborn17 commented
why was traefik chosen instead of nginx ?