Enable batching and add tests
triton-inference-server/server pull request #3714
Opened 2021-12-17 23:56 UTC by jbkyang-nvi

Testing for https://github.com/triton-inference-server/python_backend/pull/107

2021-12-20 19:20 UTC, CoderHam requested changes

2021-12-20 19:20 UTC, CoderHam commented on qa/L0_inferentia_perf_analyzer/test.sh
> +    python ${TRITON_PATH}/python_backend/inferentia/scripts/gen_triton_model.py \
A lot of these args are repeated. Why not re-use a template and add extra args instead of always using the entire (long) command.

2021-12-21 20:58 UTC, CoderHam requested changes

2021-12-21 20:58 UTC, CoderHam commented on qa/L0_inferentia_perf_analyzer/test.sh
> +# Helper function for generating models
the clear_model_dir does not generate models, move to above create_inferentia_models

2021-12-23 20:24 UTC, CoderHam approved these changes

2022-01-04 21:43 UTC, tanmayv25 approved these changes

2022-01-04 23:22 UTC, merged