Add testing for sequence models with BLS
triton-inference-server/server pull request #3826
Opened 2022-01-19 16:56 UTC by Tabrizian

2022-01-20 01:32 UTC, CoderHam submitted a review, later dismissed

2022-01-20 21:38 UTC, tanmayv25 requested changes

2022-01-20 21:38 UTC, tanmayv25 commented on qa/python_models/bls/model.py
> +    def test_bls_sequence(self):
Shouldn't we test with multiple sequences(correlation ids) as well? Two should be enough I guess. The requests from these two should be interleaved.

2022-01-21 17:41 UTC, tanmayv25 approved these changes

2022-01-21 18:40 UTC, merged