[DO NOT MERGE] Add new option to run stress and memory growth tests longer
triton-inference-server/server pull request #3889
Opened 2022-02-04 20:30 UTC by GuanLuo

must revert the change in L0_long_running_stress added for CI experiment

2022-06-29 19:17 UTC, CoderHam approved these changes

2022-06-29 22:02 UTC, tanmayv25 requested changes

2022-06-29 22:02 UTC, tanmayv25 commented on qa/L0_long_running_stress/stress.py
> +    parser.add_argument('--load-thread',
What is the purpose of having load_thread? What would a load thread count of 0 entail? Is it to keep perf_analyzer's running in the background when stress_thread is running? If yes, then we should clarify in the help message.

2022-07-07 19:13 UTC, tanmayv25 submitted a review, later dismissed

2022-07-07 20:50 UTC, CoderHam submitted a review, later dismissed

2022-07-08 02:09 UTC, tanmayv25 approved these changes

2022-07-21 19:05 UTC, merged