Add cache miss stats/metrics to server
triton-inference-server/server pull request #3964
Opened 2022-02-18 22:47 UTC by rmccorm4

Server
- [x] Add to prometheus metrics
- [x] Add to infer stats
- [x] Add to HTTP and GRPC server stats responses
- [x] Update `docs/metrics.md`
- [x] Update `docs/protocol/extension_statistics.md`

Non-server
- [x] Add cache_miss to common GRPC protobuf stub: https://github.com/triton-inference-server/common/pull/42
- [x] Separate cache_miss stat out from "overhead" in perf_analyzer output when caching enabled: https://github.com/triton-inference-server/client/pull/70

2022-02-18 23:06 UTC, rmccorm4 commented on src/core/dynamic_batch_scheduler.cc
> +      [this, queue_slot, request_hash, raw_request_ptr](
Not sure if there's a better way to do this. Passing the unique_ptr has an ownership/deletion issue

2022-02-27 22:21 UTC, rmccorm4 commented
Pipeline #4047871

2022-03-02 01:00 UTC, rmccorm4 commented on src/core/response_cache.cc
> +  auto status = BuildCacheEntry(response, &entry);
Added `ScopedTimer` class see below

2022-03-02 19:24 UTC, tanmayv25 requested changes

2022-03-02 19:24 UTC, tanmayv25 commented on src/core/response_cache.cc
> -  RETURN_IF_ERROR(BuildInferenceResponse(entry, ptr));
Is this breakdown necessary?
I believe it only adds the following message before error:
"Failed to build inference response: "

2022-03-02 19:24 UTC, tanmayv25 commented on src/core/response_cache.cc
> -  RETURN_IF_ERROR(BuildCacheEntry(response, &entry));
Same here. I think we can just leave it as :
RETURN_IF_ERROR(BuildCacheEntry(response, &entry));

2022-03-07 20:34 UTC, tanmayv25 approved these changes

2022-03-10 17:21 UTC, merged