build jar in sdk container
triton-inference-server/server pull request #4005
Opened 2022-03-02 22:41 UTC by jbkyang-nvi

Multistage build to add Java bindings jar to SDK and QA container
Actual build in client repo: https://github.com/triton-inference-server/client/pull/68

2022-03-02 23:20 UTC, dyastremsky approved these changes

2022-03-02 23:20 UTC, dyastremsky commented on Dockerfile.QA
> +        cp install/java-api-bindings/tritonserver-java-bindings.jar qa/pkgs/. ;\
Nit: If the semicolon is necessary, is the formatting right? Not "qa/pkgs/.; \"?

2022-03-02 23:54 UTC, deadeyegoodwin requested changes

2022-03-02 23:54 UTC, deadeyegoodwin commented on Dockerfile.sdk
> +# Install Java API Bindings
Can you put this at line 136 so it is next to where we build the other client components.

2022-03-08 00:33 UTC, dyastremsky submitted a review, later dismissed

2022-03-08 00:36 UTC, CoderHam submitted a review, later dismissed

2022-03-08 20:45 UTC, deadeyegoodwin submitted a review, later dismissed

2022-03-10 20:21 UTC, merged