Add HTTP raw binary request support. Add documentation in binary extension
triton-inference-server/server pull request #4070
Opened 2022-03-18 00:55 UTC by GuanLuo

2022-03-18 01:02 UTC, dyastremsky commented
Looks good! Would it make sense to add an error test case? Like if the user requests the wrong number of bytes (too many, too little). What's expected behavior and can we verify it with testing?

2022-03-18 17:58 UTC, deadeyegoodwin requested changes

2022-03-18 17:58 UTC, deadeyegoodwin commented on src/servers/http_server.cc
>    // Find Inference-Header-Content-Length in header. If missing set to 0
I think this comment is outdated

2022-03-18 17:58 UTC, deadeyegoodwin commented on qa/L0_http/http_test.py
> +class HttpTest(tu.TestResultCollector):
You should add a successful test case with BYTE type model. Also add failing test cases for BYTE type but not shape [1], fail if multiple variable-sized dimensions, fail if model has more than one input.

2022-03-18 22:47 UTC, tanmayv25 requested changes

2022-03-21 16:26 UTC, deadeyegoodwin submitted a review, later dismissed

2022-03-21 18:44 UTC, tanmayv25 approved these changes

2022-03-21 22:03 UTC, CoderHam requested changes
@GuanLuo can you rebase to resolve branch conflicts?

2022-03-22 16:54 UTC, CoderHam approved these changes

2022-03-22 17:14 UTC, merged