Add Metric API documentation and update L0_backend_identity CI test
triton-inference-server/server pull request #4211
Opened 2022-04-13 00:54 UTC by rmccorm4

2022-04-14 18:07 UTC, GuanLuo commented on docs/metrics.md
> +to manage the lifetime of their custom metrics via the C API, Triton will not
something like "The user takes the ownership of the custom metrics created through the APIs and must manage their lifetime following the API documentation"?

2022-04-14 19:01 UTC, tanmayv25 requested changes

2022-04-14 19:01 UTC, tanmayv25 commented on docs/metrics.md
> +[identity_backend](https://github.com/triton-inference-server/identity_backend)
Link to the specific section in readme for the backend once you add the behavior. In the identity backend readme too, link back to the Custom Metrics here.

2022-04-15 00:58 UTC, tanmayv25 approved these changes

2022-04-15 01:08 UTC, rmccorm4 commented
Will wait for backend PR approval to merge both at same time

2022-04-15 02:11 UTC, merged