Add some models for testing the decoupled API
triton-inference-server/server pull request #4246
Opened 2022-04-19 00:51 UTC by tanmayv25

These are few basic tests I could think of. 
These tests don't include any validating GPU tensors. I need to add those next.

2022-04-19 20:14 UTC, Tabrizian requested changes

2022-04-19 20:14 UTC, Tabrizian commented on qa/python_models/response_sender_error/model.py
> +            ).dtype == np.object_:
Same as above.

2022-04-20 14:18 UTC, Tabrizian reviewed
Can you create a side branch to merge the changes to that branch instead of `main`?

2022-04-20 21:13 UTC, Tabrizian approved these changes

2022-04-20 22:19 UTC, rmccorm4 commented on qa/python_models/decoupled_execute_error/model.py
> +        for request in requests:
This is the pythonic pattern to get the i=0, i+=1 per iteration for free
```
for i, request in enumerate(requests):
    ...
```

2022-04-21 01:48 UTC, rmccorm4 approved these changes

2022-04-21 17:26 UTC, merged