Add test for different variance of ONNX flavor
triton-inference-server/server pull request #4469
Opened 2022-06-04 00:54 UTC by GuanLuo

Followup for https://github.com/triton-inference-server/server/pull/4413

2022-06-05 06:02 UTC, Rusteam commented
thanks for handling this case!

2022-06-06 19:12 UTC, tanmayv25 requested changes

2022-06-06 19:12 UTC, tanmayv25 commented on qa/L0_mlflow/plugin_test.py
> +        # Log the ONNX model to MLFlow
Should update the description here.

2022-06-06 23:38 UTC, tanmayv25 approved these changes

2022-06-07 00:06 UTC, merged