Add testing for tf ops initialization
triton-inference-server/server pull request #4532
Opened 2022-06-21 03:08 UTC by Tabrizian

2022-06-24 21:54 UTC, Tabrizian commented on qa/common/gen_qa_tf_parameters.py
> +    print(tf.global_variables_initializer())
It is not needed. I just wanted to find out the op name. I initially though it is the variable name but looks like there was a separate operation for initialization. I'll remove this line.

2022-06-28 23:39 UTC, tanmayv25 requested changes
small change other wise looks good to me.

2022-06-28 23:39 UTC, tanmayv25 commented on qa/common/gen_qa_tf_parameters.py
> +# Copyright (c) 2021, NVIDIA CORPORATION. All rights reserved.
Need to update the years. Here and everywhere.

2022-06-29 22:05 UTC, tanmayv25 reviewed
Looks good to me. Not approving to prevent accidental merge of the PR before we move to 22.07 TF.

2022-07-11 23:05 UTC, tanmayv25 approved these changes

2022-07-12 00:04 UTC, tanmayv25 approved these changes

2022-07-12 00:10 UTC, jbkyang-nvi commented on qa/L0_tf_tag_sigdef/test.sh
> +# Copyright 2020-2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
nit: 2021-2022?

2022-07-12 00:28 UTC, tanmayv25 commented on qa/L0_tf_tag_sigdef/test.sh
> +# Copyright 2020-2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
```suggestion
# Copyright 2021-2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
```

2022-07-12 00:28 UTC, tanmayv25 approved these changes

2022-07-12 00:54 UTC, merged