Add documentation regarding GRPC streaming use case
triton-inference-server/server pull request #4575
Opened 2022-07-01 21:59 UTC by tanmayv25

Addresses #4572.

2022-07-01 22:04 UTC, rmccorm4 requested changes
minor typos

2022-07-01 22:04 UTC, rmccorm4 commented on docs/inference_protocols.md
>  Triton also implements a number [HTTP/REST and GRPC
```suggestion
Triton also implements [HTTP/REST and GRPC
```

2022-07-01 22:04 UTC, rmccorm4 commented on docs/inference_protocols.md
> +inference request. The streaming version should be used only if
```suggestion
inference requests. The streaming version should be used only if the
```

2022-07-01 22:04 UTC, rmccorm4 commented on docs/inference_protocols.md
> +* Assume a system with mulitple Triton server instances running
```suggestion
* Assume a system with multiple Triton server instances running
```

2022-07-01 22:04 UTC, rmccorm4 commented on docs/inference_protocols.md
> +  needed to hit the same Triton server instance. GRPC stream
```suggestion
  needed to hit the same Triton server instance, a GRPC stream
```

2022-07-01 22:04 UTC, rmccorm4 commented on docs/inference_protocols.md
> +  the network. GRPC stream will ensure that the server receives
```suggestion
  the network, a GRPC stream will ensure that the server receives
```

2022-07-01 22:18 UTC, rmccorm4 approved these changes

2022-07-01 22:57 UTC, jbkyang-nvi approved these changes

2022-07-04 14:28 UTC, Tabrizian approved these changes

2022-07-07 19:01 UTC, merged