Add backend support matrices for different platforms
triton-inference-server/server pull request #4760
Opened 2022-08-11 21:18 UTC by tanmayv25

2022-08-11 21:23 UTC, nv-kmcgill53 requested changes
~> https://github.com/triton-inference-server/backend/docs/backend_platform_support_matrix.md~

~I am getting 'Not Found' when attempting to follow the link~

edit: I missed the other [PR](https://github.com/triton-inference-server/backend/pull/69/files)

2022-08-11 21:42 UTC, nv-kmcgill53 submitted a review, later dismissed

2022-08-12 14:23 UTC, Tabrizian submitted a review, later dismissed

2022-08-12 16:07 UTC, rmccorm4 submitted a review, later dismissed

2022-08-15 19:38 UTC, Tabrizian approved these changes

2022-08-15 22:02 UTC, rmccorm4 approved these changes

2022-08-16 00:28 UTC, merged