Add json datatype checks
triton-inference-server/server pull request #5560
Opened 2023-03-28 17:09 UTC by Tabrizian

Common PR change: https://github.com/triton-inference-server/common/pull/84

2023-03-28 18:13 UTC, GuanLuo commented on src/http_server.cc
>          bool bool_value;
can be moved into each of the conditional

2023-03-28 18:13 UTC, GuanLuo submitted a review, later dismissed

2023-03-28 19:05 UTC, tanmayv25 requested changes

2023-03-29 19:36 UTC, tanmayv25 approved these changes

2023-03-31 16:55 UTC, dyastremsky approved these changes

2023-03-31 16:58 UTC, merged