Allow to customise args for tritonserver through values.yanl instead …
triton-inference-server/server pull request #5582
Opened 2023-04-02 11:39 UTC by okyspace

Current k8s_onprem chart has predefined args in deployment.yaml. We could change it from the yaml file though but would be cleaner to customise the args through values.yaml instead.

2023-04-04 16:45 UTC, rmccorm4 commented
Seems reasonable to me. CC @nealvaidya for comments

2023-04-04 17:28 UTC, nealvaidya commented
Looks good to me

2023-04-04 17:34 UTC, rmccorm4 requested changes
Hi @okyspace, LGTM overall, just a few things:

1. Rename additionalArgs to serverArgs to be more clear.
2. Can you also share an example command `... --set serverArgs=...` and the output showing that server deployed successfully as a sanity check?
3. Have you signed a CLA already? If not, please follow the instructions [here](https://github.com/triton-inference-server/server/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) and let us know when you've sent it.

2023-04-04 17:34 UTC, rmccorm4 commented on deploy/k8s-onprem/templates/deployment.yaml
> +            {{- range .Values.additionalArgs }}
```suggestion
            {{- range .Values.serverArgs }}
```

2023-04-04 17:34 UTC, rmccorm4 commented on deploy/k8s-onprem/values.yaml
> +additionalArgs:
```suggestion
serverArgs: 
```

2023-04-06 07:23 UTC, okyspace commented
@rmccorm4 , Thanks for your reply. 
1. I have updated the naming based on your suggestion. 
2. I can work out an example. Can advise where to provide this example?
3. I will follow up with the CLA. 

Thanks.

2023-04-20 14:47 UTC, okyspace commented
@rmccorm4, as requested, I have added the examples for sanity check. Any comments?

-------------------------------------------
The examples show how you can set the customised serverArgs and verify that they are taking effect. 

1. Execute the command below to generate the helm template to check that the serverArgs is being set correctly.  
`helm template  --set serverArgs="{'--model-repository=s3://192.168.1.110:9000/triton-models', '--repository-poll-secs=8', '--model-control-mode=poll', '--grpc-use-ssl=false'}"  triton -n triton .`

You should see the generated **deployment.yaml**. The serverArgs are populated as array args in this example. 
![image](https://user-images.githubusercontent.com/55354225/233390264-68fd7d5d-28c4-4976-a062-ef39813c5de8.png)



2. Run the container using the command. 
`helm install --set serverArgs="{'--model-repository=s3://192.168.1.110:9000/triton-models', '--repository-poll-secs=8', '--model-control-mode=poll', '--grpc-use-ssl=false'}" triton -n triton .`

Run `kubectl describe pods  -n triton`. You should see the args in the description. 
![image](https://user-images.githubusercontent.com/55354225/233389247-b9646f55-b402-4509-a387-fb8e1e16b609.png)


Once the container is successfully running, run ```kubectl logs <container id> -n triton```.
You should see these outputs that indicates the args set for the triton server. 

for e.g. model-repository, model-control-mode
![image](https://user-images.githubusercontent.com/55354225/233402005-9b6c59cf-c824-451b-9aad-561807c69812.png)

for e.g. repository-poll-secs. You can see from the logs that "Polling model repository" happens every 8 secs.
![image](https://user-images.githubusercontent.com/55354225/233401840-4959043f-8e70-472a-bd06-335490a1087e.png)

2023-04-27 00:51 UTC, okyspace commented
Hi, is there anything that I need to follow up to close this PR?

2023-05-18 01:24 UTC, yeahdongcn commented on deploy/k8s-onprem/templates/deployment.yaml
> +            - {{.}}
Nit: `{{.}}` => `{{ . }}`

2023-06-03 02:02 UTC, okyspace commented on deploy/k8s-onprem/templates/deployment.yaml
> +            - {{.}}
Thanks. Updated in my latest commit.

2023-11-15 19:37 UTC, okyspace commented
@rmccorm4 , is there something i missed out for this PR?

2024-02-21 23:04 UTC, rmccorm4 submitted a review, later dismissed
This LGTM, thanks for your patience @okyspace :bow:  Letting the linters/pre-commit run to double check.

2024-02-21 23:04 UTC, rmccorm4 commented on deploy/k8s-onprem/templates/deployment.yaml
> +          args:
```suggestion
          args:
```

2024-02-21 23:05 UTC, rmccorm4 commented on deploy/k8s-onprem/values.yaml
> +serverArgs:
```suggestion
serverArgs:
```

2024-02-21 23:05 UTC, rmccorm4 reviewed
Added suggested fixes for linter errors

2024-02-22 14:08 UTC, okyspace commented
@rmccorm4 Thanks for the reviews and suggestions.

2024-02-22 18:32 UTC, rmccorm4 approved these changes

2024-02-22 18:38 UTC, rmccorm4 commented
> I have also emailed my signed CLA.

Hi @okyspace, can you either resend this email or clarify the name/company attached to it?

2024-02-22 23:51 UTC, okyspace commented
@rmccorm4 
I have resend the CLA. 
Name: Ong Kai Yong
Company: N/A. I am not submitting on behalf of a company.

2024-03-04 19:36 UTC, merged

2024-03-04 19:37 UTC, rmccorm4 commented
Thanks for your contribution and patience @okyspace !