Mchornyi trtllm
triton-inference-server/server pull request #6687
Opened 2023-12-12 04:49 UTC by mc-nv

2023-12-12 19:31 UTC, fpetrini15 submitted a review, later dismissed

2023-12-13 00:39 UTC, krishung5 requested changes
Can you please update the name of this PR for better future reference?

2023-12-13 01:03 UTC, mc-nv commented on build.py
> -        df += trtllm_buildscript.create_postbuild(backends[be])
I compared image size on disk and it looks like my latest image is much smaller than staged one.

```
$ docker image inspect ritonserver:23.12-RC.11420617-trtllm-amd64 --format {{.Size}}
14907526249

$ docker image inspect  tritonserver:23.11-trtllm-python-py3-stage --format {{.Size}}
19851316463
```

2023-12-13 20:27 UTC, krishung5 commented on build.py
> -        df += trtllm_buildscript.create_postbuild(backends[be])
I noticed that, and this is great! But I think we could still drop those libs, and we would need to install some packages as mentioned here: https://gitlab-master.nvidia.com/ftp/tekit_backend/-/blob/main/tools/gen_trtllm_dockerfile.py?ref_type=heads#L94-96

2023-12-13 21:04 UTC, mc-nv commented on build.py
> -        df += trtllm_buildscript.create_postbuild(backends[be])
Explicit removal of the links won't give you the necessary result. 
To do so we need to introduce multistage container and limit to what we wan't to pull on top of the base container.
We can try, but  but in that case we need to maintain list of the files and libraries we wan't to care about. 
We also need to track any changes in this direction in future.

2023-12-14 18:26 UTC, mc-nv commented on build.py
> -        df += trtllm_buildscript.create_postbuild(backends[be])
@krishung5 - it's addressed

2023-12-14 18:28 UTC, mc-nv commented on build.py
I've removed it

2023-12-15 01:19 UTC, krishung5 commented
Changes lgtm! Could you re-run pre-commit to resolve the pre-commit check?

2023-12-15 04:38 UTC, mc-nv commented
> Changes lgtm! Could you re-run pre-commit to resolve the pre-commit check? 
I'm not able to solve those issues. 
Provided report is false positive, for given lines there is no issues with indentation

2023-12-19 20:05 UTC, krishung5 approved these changes

2023-12-28 17:04 UTC, merged