build: Making common.cc a self-contained object instead of including directly in executable
triton-inference-server/server pull request #7855
Opened 2024-12-06 03:13 UTC by KrishnanPrash

#### What does the PR do?
After this #7787, L0_build_variants started failing with the following error message:
```
...
=== Building wheel
=== Output wheel file is in: /workspace/build/tritonserver/build/triton-server/python/generic
[ 98%] Built target frontend-server-wheel
[100%] Linking CXX executable tritonserver
/usr/bin/ld: CMakeFiles/main.dir/common.cc.o: in function `triton::server::DecodeBase64(char const*, unsigned long, std::vector<char, std::allocator<char> >&, unsigned long&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
common.cc:(.text+0x76a): undefined reference to `base64_init_decodestate'
/usr/bin/ld: common.cc:(.text+0x77b): undefined reference to `base64_decode_block'
collect2: error: ld returned 1 exit status
gmake[5]: *** [CMakeFiles/main.dir/build.make:205: tritonserver] Error 1
gmake[4]: *** [CMakeFiles/Makefile2:411: CMakeFiles/main.dir/all] Error 2
gmake[3]: *** [Makefile:136: all] Error 2
gmake[2]: *** [CMakeFiles/triton-server.dir/build.make:86: triton-server/src/triton-server-stamp/triton-server-build] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:192: CMakeFiles/triton-server.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
error: build failed
***
*** No-Endpoint/No-Filesystem FAILED
***  
```
If we comment out the `tritonfrontend` wheel building, we get the following error message:
```
...
[ 89%] Linking CXX executable tritonserver
/usr/bin/ld: CMakeFiles/main.dir/common.cc.o: in function `triton::server::DecodeBase64(char const*, unsigned long, std::vector<char, std::allocator<char> >&, unsigned long&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/server/src/common.cc:125: undefined reference to `base64_init_decodestate'
/usr/bin/ld: /server/src/common.cc:128: undefined reference to `base64_decode_block'
collect2: error: ld returned 1 exit status
make[5]: *** [CMakeFiles/main.dir/build.make:205: tritonserver] Error 1
make[4]: *** [CMakeFiles/Makefile2:359: CMakeFiles/main.dir/all] Error 2
make[3]: *** [Makefile:136: all] Error 2
make[2]: *** [CMakeFiles/triton-server.dir/build.make:86: triton-server/src/triton-server-stamp/triton-server-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:193: CMakeFiles/triton-server.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

With the b64 dependency being introduced to `common.h`, it needs to be linked to whatever executable/library/object that uses `common.cc/common.h`. Hence, this PR builds a `common_lib` object that linked to the `tritonserver` executable and `py-bindings` shared object with the dependency directly included. 

By building `common_obj` as an object over a static/shared library, the built object files (for ex: `common.o`) will get placed directly within the executable/library/object that it is being linked to instead of creating another library that needs to be present at build time. 

#### Related PRs:
#7787

- CI Pipeline ID: 21154897

2024-12-06 18:20 UTC, fpetrini15 commented on src/CMakeLists.txt
> +add_library(common_obj OBJECT common.cc)
Where is `common.h`?

2024-12-06 22:17 UTC, GuanLuo submitted a review, later dismissed

2024-12-10 00:30 UTC, nv-kmcgill53 requested changes
> With the b64 dependency being introduced to common.h, it needs to be linked to whatever executable/library/object that uses common.cc/common.h. 

Why can't we just add the b64 lib in the compiler command line? Something like adding `-lb64` or something when the lib or executable is getting linked? This would save us from having to do this complicated common library stuff, no?

2024-12-10 00:30 UTC, nv-kmcgill53 commented on src/CMakeLists.txt
> +if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
For consistency, 
```suggestion
if (WIN32)
```

2024-12-10 00:30 UTC, nv-kmcgill53 commented on src/CMakeLists.txt
> +if (WIN32)
Is there a reason why we can't merge these two if-else block together?

2024-12-10 00:44 UTC, fpetrini15 commented
> Why can't we just add the b64 lib in the compiler command line? Something like adding -lb64 or something when the lib or executable is getting linked? This would save us from having to do this complicated common library stuff, no?

@nv-kmcgill53 I had suggested to Prasanth to make this it's own object since common owned the dependency. I figured that down the line it would help developers trace where the dependency of b64 is coming from--much like we do with the endpoint libraries. Open to your thoughts here.

2024-12-10 16:37 UTC, nv-kmcgill53 commented
I guess I don't quite see how this block of cmake makes it clearer where the b64 dependency is coming from and who is using it. If it's a library linked on the command line then it's clear that lib is needed to build everything in the repository. If the b64 lib is needed to build a different part of the repository then it's more intuitive to add the lib as a dependency to that part of the code rather than having this intermediary object get created. 

From another angle, if we were to scale your reasoning out from this single instance of `common.h` to all files of this repository, we would end up explicitly saying which libs are needed for every source file. We would then construct the command line for every source file and build independently. This is much more complicated then declaring the lib to be used for the entire repository.

Hopefully I am hearing you right, if not let's get together offline for higher bandwidth

2024-12-10 23:27 UTC, fpetrini15 commented
> We would then construct the command line for every source file and build independently. This is much more complicated then declaring the lib to be used for the entire repository.

Yeah this convinced me. Thanks for the wisdom 🙇

2024-12-12 20:04 UTC, nv-kmcgill53 approved these changes
This looks a lot better.

2024-12-13 17:12 UTC, fpetrini15 approved these changes
LGTM

2024-12-13 19:24 UTC, merged